### ISSUE TITLE
Add command

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t11-3/main#76]
Examples of add command in User Guide include:
add n/Salary d/20-2-2019 m/+50.00

However, running it will not results in invalid command format.

I would like to suggest for your add command to be able to parse different date formats such as dd-M-yyyy. Or perhaps update the add command examples.

![image](https://user-images.githubusercontent.com/8696196/55453655-50b44380-560f-11e9-833f-12373fca3714.png)

<hr>

**Reported by:** @dingheng4448
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#28]</sub>

**Comment by dingheng4448** [comment]
Sorry, there's a typo in my feedback.

It should be "However, running it results in invalid command format."
